sudo: required

language: node_js

node_js:
  - '10'

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0
    - PORT=${PORT:8080}
    - REDIS_URL = ${REDIS_URL:'redis'}

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - npm start